VA-2 app structure
SamianSoft/volcano-pwa pull request #1
Opened 2016-11-10 10:07 UTC by AliMD

It's not finished yet but need to review
مخصوصا تو ویندوز ببینید خطا نداشته باشیم!

2016-11-10 11:24 UTC, AliMD commented
Please update readme file

2016-11-10 11:37 UTC, AliMD commented
Please update cons guild

2016-11-10 11:38 UTC, AliMD commented
Please add all manifest image

2016-11-12 09:54 UTC, alirni requested changes

2016-11-12 09:54 UTC, alirni commented on index.html
> +      <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
fix tab

2016-11-12 09:54 UTC, alirni commented on test/index.html
> +    <meta charset="utf-8">
refactor to xml all file

2016-11-12 11:17 UTC, alirni approved these changes

2016-11-12 11:27 UTC, salmanclever approved these changes
ok

2016-11-12 11:28 UTC, salmanclever approved these changes
ok

2016-11-12 11:28 UTC, salmanclever approved these changes
ok

2016-11-12 11:36 UTC, alirni approved these changes

2016-11-12 11:36 UTC, merged